apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2-deployment
  labels:
    app: svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
      - name: svc2-app
        image: nazmulcs42/svc2:v1.0.1
        ports:
        - containerPort: 3000
          
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-service
spec:
  selector:
    app: svc2
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer

